#pragma once

#include <AP_HAL/AP_HAL_Boards.h>
#include "AP_ESC_Telem/AP_ESC_Telem_config.h"

#ifndef AP_FREEFLY_ALTA_X_ENABLED
#define AP_FREEFLY_ALTA_X_ENABLED HAL_WITH_ESC_TELEM && HAL_NUM_CAN_IFACES && (HAL_PROGRAM_SIZE_LIMIT_KB > 1024)
#endif

#if AP_FREEFLY_ALTA_X_ENABLED && (!HAL_WITH_ESC_TELEM || (HAL_NUM_CAN_IFACES == 0))
    #error "AP_FREEFLY_ALTA_X_ENABLED requires HAL_WITH_ESC_TELEM and CAN support"
#endif

#ifndef AP_FREEFLY_ALTA_X_ESC_COUNT_MAX
#define AP_FREEFLY_ALTA_X_ESC_COUNT_MAX 4
#endif

