#pragma once

#include <AP_HAL/AP_HAL_Boards.h>
#include "AP_ESC_Telem/AP_ESC_Telem_config.h"

#ifndef AP_FREEFLY_ALTA_X_ENABLED
#define AP_FREEFLY_ALTA_X_ENABLED HAL_WITH_ESC_TELEM && HAL_ENABLE_DRONECAN_DRIVERS  && (HAL_PROGRAM_SIZE_LIMIT_KB > 1024)
#endif

#ifndef AP_FREEFLY_ALTA_X_ESC_COUNT_MAX
#define AP_FREEFLY_ALTA_X_ESC_COUNT_MAX 4
#endif

